# -*- coding: utf-8 -*-
"""Preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4UO8wNZlXiO2AvJKFaCL_RV4iqIe_ep
"""

# ============================================================
# GOOGLE COLAB SETUP
# ============================================================
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Create the parent directory in Drive if it doesn't exist
os.makedirs("/content/drive/MyDrive/bird_classifier", exist_ok=True)

# ============================================================
# ORIGINAL IMPORTS
# ============================================================
import random
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import librosa
import librosa.effects
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from tqdm import tqdm

# ============================================================
# SHARED CONSTANTS
# ============================================================
SR           = 22050
N_MELS       = 128
N_FFT        = 2048
HOP_LENGTH   = 512
CHUNK_SEC    = 4.0
IMG_SIZE     = (224, 224)    # (height, width)
TOP_DB       = 30            # Silence trimming threshold
MEL_DB_MIN   = -80.0         # Fixed spectrogram minimum
MEL_DB_MAX   =  0.0          # Fixed spectrogram maximum

# ============================================================
# PIPELINE CONFIG
# ============================================================
# Dataset input and output paths
INPUT_DIR  = "/content/drive/MyDrive/bird_classifier/goa_birds_dataset"
OUTPUT_DIR = "/content/drive/MyDrive/bird_classifier/goa_birds_spectrograms"
AUG_PER_CHUNK = 4            # Number of augmented copies per chunk
MIN_CHUNK_DUR = 2.0          # seconds

TARGET_SPECIES = [
    "Asian_Koel",
    "Indian_Peafowl",
    "Coppersmith_Barbet",
    "Jungle_Babbler",
    "Purple-rumped_Sunbird",
    "Greater_Racket-tailed_Drongo",
    "Indian_Pitta",
    "White-throated_Kingfisher",
    "Red-wattled_Lapwing",
    "Malabar_Whistling_Thrush",
]

# ============================================================
# AUGMENTATION
# ============================================================

def augment_audio(y: np.ndarray, sr: int) -> np.ndarray:
    """
    Apply a random subset of augmentations.
    Mild enough that spectrograms still look like real bird calls.
    """
    aug = y.copy()

    # 1. Time stretch +/-15%
    if random.random() < 0.6:
        rate = random.uniform(0.85, 1.15)
        aug  = librosa.effects.time_stretch(aug, rate=rate)

    # 2. Pitch shift +/-2 semitones
    if random.random() < 0.6:
        steps = random.uniform(-2.0, 2.0)
        aug   = librosa.effects.pitch_shift(aug, sr=sr, n_steps=steps)

    # 3. Add Gaussian background noise
    if random.random() < 0.5:
        noise_amp = random.uniform(0.001, 0.008)
        aug = aug + noise_amp * np.random.randn(len(aug))

    # 4. Random gain variation
    if random.random() < 0.5:
        gain = random.uniform(0.5, 1.5)
        aug  = aug * gain

    # 5. Low-coefficient pre-emphasis
    if random.random() < 0.3:
        cutoff = random.randint(100, 500)   # Hz
        aug    = librosa.effects.preemphasis(aug, coef=cutoff / sr)

    aug = np.clip(aug, -1.0, 1.0)
    return aug

# ============================================================
# SPECTROGRAM - FIXED NORMALIZATION
# ============================================================

def audio_to_melspec_image(y: np.ndarray, sr: int, save_path: str):
    """
    Converts waveform â†’ Mel-spectrogram PNG.

    Uses FIXED vmin/vmax so every image is on the same colour scale.
    This is critical: per-sample normalisation causes the model to
    treat a loud recording and a quiet recording identically, which
    destroys relative amplitude information.
    """
    mel    = librosa.feature.melspectrogram(
        y=y, sr=sr, n_mels=N_MELS, n_fft=N_FFT, hop_length=HOP_LENGTH
    )
    mel_db = librosa.power_to_db(mel, ref=np.max)
    # Keep dB range consistent across all spectrograms.


    mel_db = np.clip(mel_db, MEL_DB_MIN, MEL_DB_MAX)

    fig, ax = plt.subplots(
        figsize=(IMG_SIZE[1] / 100, IMG_SIZE[0] / 100), dpi=100
    )
    ax.imshow(
        mel_db,
        aspect="auto",
        origin="lower",         # Low frequencies at bottom
        cmap="viridis",
        vmin=MEL_DB_MIN,        # Fixed scale
        vmax=MEL_DB_MAX,        # Fixed scale
        interpolation="nearest"
    )
    ax.axis("off")
    fig.subplots_adjust(left=0, right=1, top=1, bottom=0)
    fig.savefig(save_path, dpi=100, bbox_inches="tight", pad_inches=0)
    plt.close(fig)

# ============================================================
# CORE PIPELINE
# ============================================================

def process_species(species_name: str, in_folder: str, out_folder: str) -> int:
    os.makedirs(out_folder, exist_ok=True)

    audio_files = (list(Path(in_folder).glob("*.mp3")) +
                   list(Path(in_folder).glob("*.wav")))
    if not audio_files:
        print(f"  âš ï¸  No audio in {in_folder}")
        return 0

    chunk_samples = int(CHUNK_SEC * SR)
    chunk_count   = 0

    for audio_path in tqdm(audio_files, desc=f"  {species_name}", leave=False):
        try:
            y, _ = librosa.load(str(audio_path), sr=SR, mono=True)

            # Remove leading and trailing silence.
            y, _ = librosa.effects.trim(y, top_db=TOP_DB)

            if len(y) < MIN_CHUNK_DUR * SR:
                continue

            # Split into non-overlapping chunks.
            chunks = []
            for start in range(0, len(y) - chunk_samples + 1, chunk_samples):
                chunk = y[start : start + chunk_samples]
                if len(chunk) == chunk_samples:
                    chunks.append(chunk)

            # Pad if clip is shorter than one full chunk.
            if not chunks and len(y) >= MIN_CHUNK_DUR * SR:
                padded            = np.zeros(chunk_samples, dtype=np.float32)
                padded[:len(y)]  = y
                chunks.append(padded)

            for chunk in chunks:
                # Save original chunk spectrogram.
                fname = f"{species_name}_orig_{chunk_count:06d}.png"
                audio_to_melspec_image(
                    chunk, SR, os.path.join(out_folder, fname)
                )
                chunk_count += 1

                # Save augmented chunk spectrograms.
                for aug_idx in range(AUG_PER_CHUNK):
                    aug = augment_audio(chunk, SR)

                    # Restore exact chunk length after augmentation.
                    if len(aug) >= chunk_samples:
                        aug = aug[:chunk_samples]
                    else:
                        pad            = np.zeros(chunk_samples, dtype=np.float32)
                        pad[:len(aug)] = aug
                        aug            = pad

                    fname = f"{species_name}_aug{aug_idx}_{chunk_count:06d}.png"
                    audio_to_melspec_image(
                        aug, SR, os.path.join(out_folder, fname)
                    )
                    chunk_count += 1

        except Exception as e:
            print(f"    âŒ  {audio_path.name}: {e}")

    return chunk_count

# ============================================================
# MAIN
# ============================================================

print("ðŸ”¬  Bird Audio Preprocessing Pipeline")
print(f"   SR={SR}  n_mels={N_MELS}  chunk={CHUNK_SEC}s  "
      f"top_db={TOP_DB}  augÃ—{AUG_PER_CHUNK}")
print(f"   Spectrogram scale: [{MEL_DB_MIN}, {MEL_DB_MAX}] dB  (FIXED)\n")

os.makedirs(OUTPUT_DIR, exist_ok=True)
grand_total = 0
summary     = {}

for species in TARGET_SPECIES:
    in_folder  = os.path.join(INPUT_DIR,  species)
    out_folder = os.path.join(OUTPUT_DIR, species)

    if not os.path.isdir(in_folder):
        print(f"âš ï¸   Folder not found: {in_folder} â€” skipping")
        summary[species] = 0
        continue

    print(f"ðŸ¦  {species.replace('_', ' ')}")
    count = process_species(species, in_folder, out_folder)
    summary[species] = count
    grand_total += count
    print(f"    âœ…  {count} spectrogram PNGs saved â†’ {out_folder}\n")

# Summary
print(f"{'â•'*55}")
print("ðŸ“Š  PREPROCESSING SUMMARY")
print(f"{'â•'*55}")
for sp, count in summary.items():
    bar = "â–ˆ" * min(count // 25, 30)
    print(f"  {sp.replace('_',' '):<35}  {count:>5}  {bar}")

print(f"\n  ðŸ“  Output : {OUTPUT_DIR}/")
print(f"  ðŸ–¼ï¸   Total  : {grand_total} images")
avg = grand_total // max(len([s for s in summary.values() if s > 0]), 1)
print(f"  ðŸ“  Avg/cls : {avg}")
print(f"\nâœ…  Done. Run 3_train.py next.")
