# -*- coding: utf-8 -*-
"""Voice Download.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wn-SXmzk2OfVbm5I9kxfNXqk9SdlhYUw
"""

# ============================================================
# GOOGLE COLAB SETUP
# ============================================================
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Create the parent directory in Drive if it doesn't exist
parent_dir = '/content/drive/MyDrive/bird classifier'
os.makedirs(parent_dir, exist_ok=True)

# ============================================================
# ORIGINAL IMPORTS
# ============================================================
import requests
import time
import urllib.request
from pathlib import Path

# ============================================================
# CONFIG
# ============================================================
API_KEY        = "3eaefa2719a49ba41a20868315e95325e1e8b02f"
# Dataset path in Google Drive
BASE_DIR       = "/content/drive/MyDrive/bird classifier/goa_birds_dataset"
DOWNLOAD_LIMIT = 150          # Maximum files to download per species
MAX_DURATION   = 180          # seconds
MIN_DURATION   = 3            # Minimum clip length in seconds
QUALITY_FILTER = {"A", "B", "C", "D"}
TYPE_FILTER    = {"call", "song"}
RETRY_LIMIT    = 3            # Retry count for failed requests
API_V3         = "https://xeno-canto.org/api/3/recordings"

# ============================================================
# TARGET SPECIES
# ============================================================
birds_dict = {
    # Core training species
    "Asian_Koel":                   "Eudynamys scolopaceus",
    "Indian_Peafowl":               "Pavo cristatus",
    "Coppersmith_Barbet":           "Psilopogon haemacephalus",
    "Jungle_Babbler":               "Argya striata",
    "Purple-rumped_Sunbird":        "Leptocoma zeylonica",
    "Greater_Racket-tailed_Drongo": "Dicrurus paradiseus",
    "Indian_Pitta":                 "Pitta brachyura",
    "White-throated_Kingfisher":    "Halcyon smyrnensis",
    "Red-wattled_Lapwing":          "Vanellus indicus",
    "Malabar_Whistling_Thrush":     "Myophonus horsfieldii",
}

os.makedirs(BASE_DIR, exist_ok=True)

# ============================================================
# HELPERS
# ============================================================

def parse_duration(s: str) -> int:
    try:
        parts = [int(x) for x in s.strip().split(":")]
        return (parts[0] * 60 + parts[1]) if len(parts) == 2 \
               else (parts[0] * 3600 + parts[1] * 60 + parts[2])
    except Exception:
        return 9999


def build_query(sci_name: str) -> str:
    """'Pavo cristatus' â†’ 'gen:Pavo+sp:cristatus'  (v3 tag format)"""
    parts = sci_name.strip().split()
    return f"gen:{parts[0]}+sp:{parts[1]}"


def fetch_page(sci_name: str, page: int) -> dict | None:
    url = f"{API_V3}?query={build_query(sci_name)}&key={API_KEY}&page={page}"
    for attempt in range(1, RETRY_LIMIT + 1):
        try:
            r = requests.get(url, timeout=25,
                             headers={"User-Agent": "BirdClassifierProject/1.0"})
            if r.status_code == 200:
                data = r.json()
                if "recordings" in data:
                    return data
                print(f"    âš ï¸  Unexpected response: {list(data.keys())}")
                return None
            print(f"    HTTP {r.status_code} (attempt {attempt}/{RETRY_LIMIT})")
        except Exception as e:
            print(f"    Exception (attempt {attempt}/{RETRY_LIMIT}): {e}")
        time.sleep(2 ** attempt)   # Exponential back-off before retry
    return None


def download_file(file_url: str, dest: str) -> bool:
    if file_url.startswith("//"):
        file_url = "https:" + file_url
    for attempt in range(1, RETRY_LIMIT + 1):
        try:
            opener = urllib.request.build_opener()
            opener.addheaders = [("User-Agent", "BirdClassifierProject/1.0")]
            urllib.request.install_opener(opener)
            urllib.request.urlretrieve(file_url, dest)
            # Reject empty or corrupt files.
            if Path(dest).stat().st_size < 2048:
                Path(dest).unlink(missing_ok=True)
                print(f"      âš ï¸  File too small â€” skipped")
                return False
            return True
        except Exception as e:
            print(f"      âŒ Attempt {attempt}/{RETRY_LIMIT}: {e}")
            time.sleep(2 ** attempt)
    return False


# ============================================================
# MAIN
# ============================================================

print("ðŸš€  Xeno-canto Downloader  [API v3]\n")
summary = {}

for common_name, sci_name in birds_dict.items():
    print(f"\n{'â”€'*60}")
    print(f"ðŸ¦  {common_name.replace('_',' ')}  [{sci_name}]")

    outdir = os.path.join(BASE_DIR, common_name)
    os.makedirs(outdir, exist_ok=True)

    # Resume download by counting existing files first.
    existing = len(list(Path(outdir).glob("*.mp3")))
    if existing >= DOWNLOAD_LIMIT:
        print(f"  âœ…  Already have {existing} files â€” skipping download")
        summary[common_name] = existing
        continue

    downloaded, skipped = existing, 0
    page, total_pages   = 1, 1

    while page <= total_pages and downloaded < DOWNLOAD_LIMIT:
        print(f"  ðŸ“„  Page {page}/{total_pages}  |  downloaded so far: {downloaded}")
        data = fetch_page(sci_name, page)
        if data is None:
            print("  â›”  API returned no data â€” skipping species.")
            break

        total_pages = int(data.get("numPages", 1))
        print(f"        â†’ {data.get('numRecordings','?')} total recordings | "
              f"{total_pages} page(s)")

        recordings = data.get("recordings", [])
        if not recordings:
            break

        for rec in recordings:
            if downloaded >= DOWNLOAD_LIMIT:
                break

            q        = rec.get("q", "").strip().upper()
            duration = parse_duration(rec.get("length", "0:00"))
            rtype    = rec.get("type", "").lower()
            file_url = rec.get("file", "")

            if q not in QUALITY_FILTER:
                skipped += 1; continue
            if not (MIN_DURATION <= duration <= MAX_DURATION):
                skipped += 1; continue
            if not any(t in rtype for t in TYPE_FILTER):
                skipped += 1; continue
            if not file_url:
                skipped += 1; continue

            rec_id    = rec.get("id", "unknown")
            file_path = os.path.join(outdir, f"{common_name}_XC{rec_id}.mp3")

            if Path(file_path).exists():
                downloaded += 1
                continue

            if download_file(file_url, file_path):
                downloaded += 1
                print(f"    âœ…  [{downloaded}/{DOWNLOAD_LIMIT}]  XC{rec_id} | "
                      f"q:{q} | {rec.get('length','?')} | {rtype}")

            time.sleep(1.2)   # Small delay to avoid aggressive request rate

        page += 1
        time.sleep(1.5)

    summary[common_name] = downloaded
    print(f"  ðŸŽ¯  Done: {downloaded} downloaded, {skipped} filtered out")

# Summary
print(f"\n{'â•'*60}")
print("ðŸ“Š  FINAL SUMMARY")
print(f"{'â•'*60}")
total = 0
for name, count in summary.items():
    flag  = "âœ…" if count >= 100 else ("âš ï¸ " if count >= 50 else "âŒ")
    total += count
    print(f"  {flag}  {name.replace('_',' '):<38}  {count:>3} / {DOWNLOAD_LIMIT}")

print(f"\n  Total files downloaded : {total}")

low = [n for n, c in summary.items() if c < 50]
if low:
    print("\nâš ï¸  Very low data species (consider re-running or augmenting more):")
    for n in low:
        print(f"     â€¢ {n.replace('_',' ')}")

print("\nâœ…  Done! Run 2_preprocess.py next.")

